version: '3.1'

services:

  master:
    container_name: master
    build:
      context: .
      dockerfile: ./master/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: hamed
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hamed
      PG_REP_USER: rep
      PG_REP_PASSWORD: 123456
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./replicant:/opt/replicant/replicant
    ports:
    - 80:8080

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
#    ports:
#    - 80:80