version: '3.1'

services:

  master:
    container_name: master
    build:
      context: .
      dockerfile: ./master/Dockerfile
    environment:
      POSTGRES_USER: hamed
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hamed
      PG_REP_USER: rep
      PG_REP_PASSWORD: 123456
    volumes:
      #- ./pg_data:/var/lib/postgresql/data
      - ./replicant:/opt/replicant/replicant
      - ./master/conf.ini:/opt/replicant/replicant/conf.ini
    ports:
    - 80:8080


  replica:
    container_name: replica
    build:
      context: .
      dockerfile: ./replica/Dockerfile
    environment:
      POSTGRES_USER: hamed
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hamed
      PG_REP_USER: rep
      PG_REP_PASSWORD: 123456
      PG_MASTER_HOST: master
    volumes:
      #- ./pg_data:/var/lib/postgresql/data
      #- ./replicant:/opt/replicant/replicant
      - ./replica/conf.ini:/opt/replicant/replicant/conf.ini
    depends_on:
      - master
    ports:
      - 8080:8080

  arbiter:
    container_name: arbiter
    build:
      context: .
      dockerfile: ./replica/Dockerfile
    environment:
      POSTGRES_USER: hamed
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hamed
      PG_REP_USER: rep
      PG_REP_PASSWORD: 123456
      PG_MASTER_HOST: master
    volumes:
      #- ./pg_data:/var/lib/postgresql/data
      #- ./replicant:/opt/replicant/replicant
      - ./arbiter/conf.ini:/opt/replicant/replicant/conf.ini
    depends_on:
      - master
    ports:
      - 8070:8080